import Hero from "@/components/Hero";
import SectionHeading from "@/components/SectionHeading";
import FeaturedHotelCard from "@/components/FeaturedHotelCard";
import RoomCard from "@/components/RoomCard";
import BlogCard from "@/components/BlogCard";
import FAQAccordion from "@/components/FAQAccordion";
import ContactSection from "@/components/ContactSection";
import Link from "next/link";
import { blogPosts } from "@/data/blog";
import { roomTypes, siteImages } from "@/data/site";
import { Icon } from "@/components/Icon";
import SiteImage from "@/components/SiteImage";
import IslandTicker from "@/components/IslandTicker";

const discovery = [
  ["Avşa’ya Nasıl Gidilir?","İstanbul, Erdek ve Tekirdağ bağlantılarını karşılaştırın.","/avsa-ulasim","↗"],
  ["Avşa’da Nerede Kalınır?","Merkez, koylar ve tesis seçeneklerini tatil ritminize göre seçin.","/avsa-otelleri","⌖"],
  ["Avşa Plajları","Merkez Plajı’ndan Çınar ve Altınkum’a kıyı rotaları.","/blog/avsa-plajlari-rehberi","≈"],
  ["Aile Tatili","Çocuklarla rahat bir ada programı için pratik notlar.","/blog/avsada-cocuklu-tatil-onerileri","☀"],
  ["Havuzlu Otel Önerisi","Deniz ve havuzu aynı tatilde birleştiren konaklama yaklaşımı.","/havuz-aquapark","◌"],
  ["Gezilecek Yerler","Sahil yolu, çarşı, Yiğitler ve koylarda sakin keşifler.","/avsa-rehberi","✦"],
] as const;

export default function Home(){return <><Hero/><IslandTicker/>
  <section className="section pt-28 md:pt-40"><div className="container"><SectionHeading eyebrow="Neden Avşa?" title="Ada tatilinin hafif ve özgür hâli" description="Kısa bir hafta sonundan uzun bir aile tatiline kadar Avşa; deniz ulaşımı, farklı plajları ve yürünebilir ada yaşamıyla planınıza uyum sağlar." center/><div className="grid md:grid-cols-3 gap-5">{[["01","Denizle başlayan yolculuk","İstanbul, Erdek ve Tekirdağ yönlerinden sezonluk deniz ulaşımı seçeneklerini karşılaştırın."],["02","Her güne başka bir kıyı","Merkez Plajı’ndan Çınar, Altınkum ve Karadut çevresine uzanan farklı koyları keşfedin."],["03","Ailelerin kendi ritmi","Plajı, havuzu ve kısa ada gezilerini çocukların temposuna göre aynı programda birleştirin."]].map(([n,t,d])=><article className="card editorial-card p-7 md:p-8" key={n}><span className="section-number">{n}</span><h3 className="font-[Georgia] text-2xl text-[#073b4c] mt-8">{t}</h3><p className="text-[#637a80] leading-7 mt-3">{d}</p></article>)}</div></div></section>

  <section className="section soft-section"><div className="container relative"><div className="grid lg:grid-cols-[.72fr_1.28fr] gap-10 items-end mb-10"><SectionHeading eyebrow="Avşa’da nerede kalınır?" title="Konaklamayı tatil tarzınıza göre seçin"/><p className="lead lg:pb-10">Avşa otelleri arasında karar verirken yalnızca gecelik fiyatı değil; plaja erişimi, oda düzenini, merkeze yakınlığı ve aile ihtiyaçlarını birlikte değerlendirin.</p></div><div className="grid md:grid-cols-3 gap-4">{[["Merkez ve sahil","Çarşıya, iskeleye ve akşam yürüyüşlerine yakın olmak isteyenler için pratik bir başlangıç.","⌖"],["Avşa’da havuzlu otel","Çocuklu aileler ve denize alternatif bir tesis günü planlayanlar için esnek bir seçenek.","≈"],["Koylara yakın bölgeler","Daha sakin sabahlar ve doğayla iç içe bir ada ritmi isteyenler için.","☼"]].map(([t,d,icon])=><Link href="/avsa-otelleri" key={t} className="card group p-7 bg-white/80 hover:-translate-y-1"><span className="w-14 h-14 rounded-[20px] bg-gradient-to-br from-[#dff7f4] to-[#fff5d8] grid place-items-center text-[#007f91] text-xl mb-8">{icon}</span><h3 className="font-[Georgia] text-2xl text-[#073b4c]">{t}</h3><p className="text-sm leading-7 text-[#647a80] my-4">{d}</p><span className="text-sm font-bold text-[#007f91] inline-flex items-center gap-2">Avşa otelleri rehberi <Icon name="arrow" size={17}/></span></Link>)}</div></div></section>

  <section className="section"><div className="container"><div className="flex flex-col md:flex-row justify-between md:items-end gap-5 mb-10"><SectionHeading eyebrow="Öne çıkan tesis" title="Avşa’da aile dostu, havuzlu bir konaklama önerisi"/><Link href="/avsa-otelleri" className="btn btn-outline shrink-0">Otel seçme rehberi</Link></div><FeaturedHotelCard/></div></section>

  <section className="section bg-[#eef8f6]"><div className="container"><SectionHeading eyebrow="Konaklama seçenekleri" title="Ailenize uygun oda düzenini keşfedin" description="Oda adları ve görseller, güncel tesis içerikleri eklendiğinde kolayca değiştirilebilecek component yapısında hazırlandı."/><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{roomTypes.map(r=><RoomCard key={r.name} room={r}/>)}</div><div className="text-center mt-10"><Link href="/odalar" className="btn btn-outline">Tüm odaları incele <Icon name="arrow" size={17}/></Link></div></div></section>

  <section className="section dark-section"><div className="container"><div className="grid lg:grid-cols-[.8fr_1.2fr] gap-10 items-end mb-10"><SectionHeading eyebrow="Avşa’yı keşfedin" title="Bir tatilden fazlası: küçük bir ada ritüeli"/><p className="lead lg:pb-10">Gününüzü tesadüfe bırakmadan, tatilin rahatlığını da kaybetmeden planlayın. Ulaşım, plaj ve konaklama rehberleri tek bir keşif alanında.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{discovery.map(([t,d,h,icon],i)=><Link key={t} href={h} data-number={String(i+1).padStart(2,"0")} className="discover-card"><span className="w-11 h-11 rounded-2xl bg-white/12 border border-white/15 grid place-items-center text-[#f3bd4d] text-xl mb-auto">{icon}</span><h3 className="font-[Georgia] text-2xl text-white mt-8">{t}</h3><p className="text-white/60 text-sm leading-6 mt-3">{d}</p><span className="text-[#f3bd4d] font-bold text-sm mt-5 inline-flex gap-2">Rehberi aç <Icon name="arrow" size={17}/></span></Link>)}</div></div></section>

  <section className="section"><div className="container grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center"><div className="relative"><SiteImage src={siteImages.aquapark.src} alt={siteImages.aquapark.alt} sizes="(max-width: 1024px) 100vw, 52vw" className="h-[430px] md:h-[560px] rounded-[42px_42px_130px_42px] shadow-[0_30px_80px_#073b4c22]"><div className="absolute inset-0 z-[1] bg-gradient-to-t from-[#032e3c66] via-transparent to-transparent"/><span className="absolute z-[2] top-6 left-6 bg-white/90 backdrop-blur rounded-full py-2 px-4 text-xs font-bold text-[#075663]">ATAŞ AQUA OTEL • AQUAPARK</span></SiteImage><div className="absolute z-[3] -bottom-5 -right-2 md:-right-7 glass rounded-3xl p-5 max-w-[250px]"><strong className="font-[Georgia] text-xl text-[#073b4c]">Deniz + havuz</strong><p className="text-xs text-[#55747b] leading-5 mt-1">Hava ve çocukların temposuna göre esnek tatil planı.</p></div></div><div><SectionHeading eyebrow="Çocuklu aileler için" title="Havuz, ada tatiline esneklik katar" description="Havuz ve aquapark, rüzgârlı saatlerde veya tesiste dinlenmek istediğiniz bir günde aile programına alternatif sunabilir."/><div className="grid gap-3">{["Çocuklar için tesiste alternatif aktivite","Ebeveynler için plaj dışında dinlenme kolaylığı","Deniz ve havuzu aynı güne sığdıran esnek program"].map(x=><div key={x} className="card !rounded-2xl px-5 py-4 flex items-start gap-3"><span className="mt-0.5 text-[#007f91]"><Icon name="check"/></span><span className="font-bold text-[#31545d]">{x}</span></div>)}</div><Link href="/havuz-aquapark" className="btn btn-primary mt-7">Avşa havuzlu otel rehberi <Icon name="arrow" size={17}/></Link></div></div></section>

  <section className="section soft-section"><div className="container"><div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-10"><SectionHeading eyebrow="Ada günlüğü" title="Tatil planınıza eşlik eden seçilmiş rehberler"/><Link href="/blog" className="btn btn-outline shrink-0">40 rehberin tamamı</Link></div><div className="grid lg:grid-cols-[1.25fr_.75fr] gap-5"><BlogCard post={blogPosts[0]} featured/><div className="grid sm:grid-cols-2 lg:grid-cols-1 gap-5">{blogPosts.slice(1,3).map(p=><BlogCard post={p} key={p.slug}/>)}</div></div></div></section>

  <section className="section"><div className="container grid lg:grid-cols-[.72fr_1.28fr] gap-12"><SectionHeading eyebrow="Merak edilenler" title="Avşa tatili hakkında kısa ve net cevaplar" description="Yola çıkmadan önce en sık sorulan başlıkları bir araya getirdik."/><FAQAccordion/></div></section>
  <section className="section pt-0"><div className="container"><ContactSection/></div></section>
  </>}
