import type { Metadata } from "next"; import GuideLayout from "@/components/GuideLayout";
export const metadata:Metadata={title:"Avşa Otelleri: Konaklama Seçim Rehberi",description:"Avşa otelleri arasında seçim yaparken konum, plaj, aile olanakları, havuz ve fiyat-performans açısından dikkat edilmesi gerekenler.",alternates:{canonical:"/avsa-otelleri"}};
export default function Page(){return <GuideLayout eyebrow="Konaklama rehberi" title="Avşa Otelleri: Konaklama Seçimi Yaparken Nelere Dikkat Etmelisiniz?" description="Çok otelli bir liste değil; ihtiyaçlarınıza uygun tesisi seçmeniz için şeffaf bir karar rehberi." sections={[
  {title:"Önce bölgeyi ve konumu seçin",body:"Merkeze, plaja ve akşam yürüyüş rotalarına yakınlık tatil ritminizi doğrudan etkiler. Haritada görünen kısa mesafenin yokuş, yol yapısı ve çocuklarla yürüyüş açısından ne ifade ettiğini tesise sorun.",points:["İskele ve merkeze erişim","Plaja yürüme mesafesi","Akşam ulaşım seçenekleri","Park veya transfer bilgisi"]},
  {title:"Aile otelinde ayrıntılar önemlidir",body:"Çocuklu tatilde oda kapasitesi kadar güvenli ortak alan, gölgelik, kahvaltı saati ve havuz kullanım koşulları da konforu belirler.",points:["Çocuk yatağı imkânı","Oda kapasitesi","Havuz güvenlik kuralları","Sessizlik ve dinlenme düzeni"]},
  {title:"Havuz ve aquapark avantajı",body:"Deniz koşullarının değiştiği saatlerde havuz tesiste alternatif bir gün sunar. Aquaparklı tesislerde yaş ve boy sınırı ile gözetim kurallarını rezervasyon öncesinde teyit edin."},
  {title:"Fiyat-performansı doğru karşılaştırın",body:"Toplam fiyata kahvaltı, klima, oda temizliği ve diğer hizmetlerin dahil olup olmadığını sorun. İptal koşulları ve ön ödeme bilgisini yazılı olarak alın.",points:["Dahil hizmetler","İptal ve değişiklik","Erken rezervasyon","Doğrudan teyit"]},
  {title:"Öne çıkan öneri: Ataş Aqua Otel",body:"Avşa’da havuzlu ve aile dostu tesis arayanlar için öne çıkan önerimiz Ataş Aqua Otel. Bu sitedeki tüm rezervasyon akışları yalnızca bu tesis için çalışır; çok otelli rezervasyon platformu değiliz."}
]}/>}
