"use client";
import { FormEvent, useState } from "react"; import { roomTypes, whatsappUrl } from "@/data/site";
type Props={compact?:boolean;defaultRoom?:string};
export default function BookingWidget({compact=false,defaultRoom=""}:Props){
  const [error,setError]=useState("");
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);const required=["name","phone","checkin","checkout"] as const;const missing=required.some(k=>!String(f.get(k)||"").trim());if(missing){setError(compact?"Lütfen telefon, giriş ve çıkış tarihlerini doldurun.":"Lütfen ad soyad, telefon ve tarih alanlarını doldurun.");return}const ci=new Date(String(f.get("checkin")));const co=new Date(String(f.get("checkout")));if(co<=ci){setError("Çıkış tarihi giriş tarihinden sonra olmalıdır.");return}const msg=`Merhaba, Avşa Tatil Rehberi üzerinden Ataş Aqua Otel için rezervasyon bilgisi almak istiyorum.\nGiriş tarihi: ${f.get("checkin")}\nÇıkış tarihi: ${f.get("checkout")}\nYetişkin: ${f.get("adult")}\nÇocuk: ${f.get("child")}\nAd Soyad: ${f.get("name")}\nTelefon: ${f.get("phone")}\nOda tercihi: ${f.get("room")||"Belirtilmedi"}\nNot: ${f.get("note")||"-"}`;window.open(whatsappUrl(msg),"_blank","noopener,noreferrer")}
  const field="h-12 w-full rounded-xl border border-[#cbdedd] bg-white px-4 outline-none focus:ring-2 focus:ring-[#62c7c2] text-sm min-w-0";
  return <form onSubmit={submit} className={`card booking-search ${compact?"p-4 md:p-5":"p-5 md:p-8"}`} noValidate><div className="flex items-center justify-between gap-3 mb-4"><div><span className="eyebrow">{compact?"Hızlı müsaitlik":"Rezervasyon talebi"}</span><strong className="hidden md:block text-[#073b4c] mt-1">{compact?"Tarihlerinizi seçin, WhatsApp’tan bilgi alın":"Konaklama bilgilerinizi paylaşın"}</strong></div><span className="hidden sm:inline-flex text-[10px] font-bold text-[#477078] bg-[#eaf7f5] px-3 py-2 rounded-full">Kesin rezervasyon oluşturmaz</span></div><div className={`grid gap-3 ${compact?"sm:grid-cols-2 lg:grid-cols-6":"md:grid-cols-2"}`}>
    {!compact&&<><label className="grid gap-2 text-xs font-bold">Ad Soyad<input name="name" className={field} placeholder="Adınız ve soyadınız"/></label><label className="grid gap-2 text-xs font-bold">Telefon<input name="phone" type="tel" className={field} placeholder="05__ ___ __ __"/></label></>}
    <label className="grid gap-2 text-xs font-bold">Giriş tarihi<input name="checkin" type="date" className={field}/></label><label className="grid gap-2 text-xs font-bold">Çıkış tarihi<input name="checkout" type="date" className={field}/></label><label className="grid gap-2 text-xs font-bold">Yetişkin<select name="adult" className={field} defaultValue="2">{[1,2,3,4,5,6].map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-2 text-xs font-bold">Çocuk<select name="child" className={field} defaultValue="0">{[0,1,2,3,4].map(x=><option key={x}>{x}</option>)}</select></label>
    {compact?<label className="grid gap-2 text-xs font-bold">Telefon<input name="phone" type="tel" className={field} placeholder="05__ ___ __ __"/></label>:<><label className="grid gap-2 text-xs font-bold">Oda tercihi<select name="room" className={field} defaultValue={defaultRoom}><option value="">Fark etmez</option>{roomTypes.map(room=><option key={room.name}>{room.name}</option>)}</select></label><label className="grid gap-2 text-xs font-bold">Not<textarea name="note" className={`${field} !h-24 py-3`} placeholder="Çocuk yaşları, özel isteğiniz..."/></label></>}
    {compact&&<input type="hidden" name="name" value="Hızlı bilgi talebi"/>}<button className="btn btn-sun self-end !rounded-xl !h-12 px-3 text-sm" type="submit">{compact?"WhatsApp’tan Bilgi Al":"Rezervasyon Talebi Gönder"}</button>
  </div>{error&&<p role="alert" className="text-sm text-red-700 bg-red-50 p-3 rounded-xl mt-3">{error}</p>}<p className="text-[11px] text-[#71868b] mt-3 leading-5">Bilgileriniz bir WhatsApp mesajına dönüştürülür; göndermeden önce kontrol edebilirsiniz.</p></form>
}
